// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.3 DO NOT EDIT.
package openapi

// Task model definition
type Task struct {
	Description string `json:"description"`
	Id          int    `json:"id"`
	IsDeleted   bool   `json:"isDeleted"`
	IsFinished  bool   `json:"isFinished"`
	Title       string `json:"title"`
	Version     int    `json:"version"`
}

// PostTaskJSONBody defines parameters for PostTask.
type PostTaskJSONBody struct {
	Description *string `json:"description,omitempty"`
	Title       *string `json:"title,omitempty"`
}

// PatchTasksTaskIdJSONBody defines parameters for PatchTasksTaskId.
type PatchTasksTaskIdJSONBody struct {
	Description *string `json:"description,omitempty"`
	Title       *string `json:"title,omitempty"`
}

// PostTaskJSONRequestBody defines body for PostTask for application/json ContentType.
type PostTaskJSONRequestBody PostTaskJSONBody

// PatchTasksTaskIdJSONRequestBody defines body for PatchTasksTaskId for application/json ContentType.
type PatchTasksTaskIdJSONRequestBody PatchTasksTaskIdJSONBody

